"""empty message

Revision ID: 23ee63319e69
Revises: 5635bd8f9001
Create Date: 2021-04-11 15:10:49.320817

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '23ee63319e69'
down_revision = '5635bd8f9001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movie_actor')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie_actor',
    sa.Column('actor_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('movie_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['actor.id'], name='movie_actor_ibfk_1'),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], name='movie_actor_ibfk_2'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
