"""empty message

Revision ID: 6f4bfc25f1aa
Revises: 
Create Date: 2021-04-10 17:01:58.101894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f4bfc25f1aa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cinematheque_movie',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('length', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.DateTime(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cinematheque_movie')
    # ### end Alembic commands ###
